server:
  port: @quartzport@
  ip: @quartzip@
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 1048576000
    max-threads: 1000
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: @dburl@
      username: @dbusername@
      password: @dbpassword@
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  resources:
    static-locations: classpath:static/,file:static/
  quartz:
    job-store-type: jdbc
    auto-startup: true
    jdbc:
      initialize-schema: never
      schema: classpath:/sql/quartztables.sql
    overwrite-existing-jobs: true
  application:
    name: mol-quartz
#注册中心地址
eureka:
  client:
    service-url:
      defaultZone: @eurekaserverurl@
  instance:
    prefer-ip-address: true
    instance-id=${server:ip}:${server:port}:

supplieragentid: @supplieragentid@
expertagentid: @expertagentid@
purchaseagentid: @purchaseagentid@

logging:
  level:
    com.mol.quartz.mapper: debug
  file: /usr/local/log/${spring.application.name}/${spring.application.name}.log
  file.max-history: 60


